Add historic data

diff --git a/.github/workflows/node-lambda-mocha.yml b/.github/workflows/node-lambda-mocha.yml
--- a/.github/workflows/node-lambda-mocha.yml
+++ b/.github/workflows/node-lambda-mocha.yml
@@ -57,6 +57,101 @@ jobs:
         with:
           path: ${{ github.workspace }}/coverage/cobertura-coverage.xml
           branch_minimum_threshold: ${{ inputs.BRANCH_THRESHOLD }}
+        
+      # Compare against historic coverage (BRANCH_THRESHOLD is empty or 0, AWS secrets populated)
+      # Historic data stored in a CSV file in S3, and is updated if coverage improves.
+      - name: Configure AWS credentials
+        if: ${{ inputs.BRANCH_THRESHOLD <= 0 }}
+        uses: aws-actions/configure-aws-credentials@v1
+        with:
+          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
+          role-duration-seconds: 900
+          aws-region: ${{ inputs.AWS_REGION }}
+
+      - name: Check Branch Coverage against historic data
+        if: ${{ inputs.BRANCH_THRESHOLD <= 0 }}
+        env:
+          REPO: ${{ github.repository }}
+          BRANCH: ${{ github.ref_name }}
+          COVERAGE_S3_PATH: ${{ inputs.COVERAGE_S3_PATH }}
+          NEVER_FAIL_AT: ${{ inputs.NEVER_FAIL_AT }}
+          PERSIST: false
+          DEBUG: ${{ inputs.DEBUG }}
+        run: |
+          # Utility Functions
+          log_debug() {
+            if [ "$DEBUG" = "true" ]; then echo $@; fi
+          }
+          get_branch() {
+              if [ -f "$1" ]; then
+                  raw=$(cat "$1" | sed -e 's/\r//g' | grep -Po --color=never '<coverage.+branch-rate="\K[^"]+')
+                  echo "$raw * 100" | bc -l | head -c 6
+              else
+                  echo 0
+              fi
+          }
+          get_record() {
+                  local record=$(cat coverage.csv | grep "^$1,$2,")
+                  [ -z "$record" ] && record=$(cat coverage.csv | grep "^$1,$3,")
+                  echo $record
+          }
+
+          # Set behaviour based on current branch
+          [ "$BRANCH" = "main" ] && PERSIST=true
+          [ "$BRANCH" = "main" ] || BRANCH=latest
+
+          # Retrieve or create coverage CSV
+          aws s3 cp --quiet $COVERAGE_S3_PATH coverage.csv || true
+          if [ ! -f "coverage.csv" ]
+          then
+              log_debug "coverage.csv not present, creating placeholder"
+              echo "Repository,Branch,Total Branch Rate,Integration Branch Rate,Unit Branch Rate"  > coverage.csv
+              PERSIST=true
+          else
+              log_debug "coverage.csv downloaded OK"
+          fi
+
+          # Parse current branch coverage
+          total_rate=$(get_branch "$GITHUB_WORKSPACE/coverage/cobertura-coverage.xml")
+          integ_rate=0
+          unit_rate=$total_rate
+          echo "Branch coverage rates for $REPO@$BRANCH -- Total: $total_rate, IntegrationTests: $integ_rate, UnitTests: $unit_rate"
+
+          # Parse historic coverage and cross-check
+          record=$(get_record "$REPO" "main" "latest")
+          log_debug "$record"
+
+          if [ -n "$record" ]
+          then
+              total_persist=$(echo $record | cut -d, -f3)
+              integ_persist=$(echo $record | cut -d, -f4)
+              unit_persist=$(echo $record | cut -d, -f5)
+
+              if (( $(echo "$total_persist > $total_rate" | bc -l) ))
+              then
+                  if (( $(echo "$NEVER_FAIL_AT < $total_rate" | bc -l) ))
+                  then
+                      echo "::notice title=Branch coverage fallen::Test coverage has dropped from $total_persist to $total_rate, but is still above $NEVER_FAIL_AT"
+                  else
+                      echo "::error title=Branch coverage failure::Test coverage has dropped from $total_persist to $total_rate"
+                      exit 1
+                  fi
+              else
+                  echo "::notice title=Branch coverage maintained::Test coverage maintained from $total_persist to $total_rate"
+              fi
+
+              # Remove current coverage values
+              cat coverage.csv | grep -v "^$REPO,$BRANCH," > repos.tmp
+              mv repos.tmp coverage.csv
+          else
+              echo "::notice::First time coverage reporting for $REPO@$BRANCH. Coverage is $total_rate"
+          fi
+
+          # Add new coverage values and persist
+          echo "$REPO,$BRANCH,$total_rate,$integ_rate,$unit_rate" >> coverage.csv
+          [ "$PERSIST" = "true" ] && aws s3 cp --quiet coverage.csv $COVERAGE_S3_PATH
+
+          exit 0
 
       - name: List files in case of failure
         if: failure()
