Implement checking against historic test coverage
- Store last-seen coverage values for each repo in a CSV (uploaded to S3)
- Run tests and generate coverage reports as previously
- Instead of using the existing `BRANCH_THRESHOLD` parameter, use the last seen-value from previous runs
  - If current test coverage is lower, then fail
  - If test coverage higher, persist the higher value to S3

Required change to calling workflows as follows:
- Add AWS related secrets
- Instead of specifying `BRANCH_THRESHOLD`, set `COVERAGE_S3_PATH` to indicate where the CSV lives

Updated workflow is backwards compatible, so using the existing input parameters without specifying the new ones will simply use the legacy behaviour. This is done by testing whether `BRANCH_THRESHOLD` is populated or not.

diff --git a/.github/workflows/xunit.yml b/.github/workflows/xunit.yml
--- a/.github/workflows/xunit.yml
+++ b/.github/workflows/xunit.yml
@@ -5,15 +5,28 @@ name: Run XUnit Tests
 on:
   workflow_call:
     inputs:
-      BRANCH_THRESHOLD: # Test coverage threshold (integer): workflow will fail if branch coverage does not meet or exceed this threshold
-        required: true
-        type: number
       DOCKER_COMPOSE:   # Path to docker-compose.yml file: If populated, spins up containers required for integration tests
         type: string
+      BRANCH_THRESHOLD: # Test coverage threshold (integer): workflow will fail if branch coverage does not meet or exceed this threshold
+                        # If NOT populated, use historic data from previous runs as the threshold.
+                        # Historic data stored in S3, so the AWS secrets must be populated in this instance
+        type: number
+        default: 0
+      COVERAGE_S3_PATH: # S3 path of the CSV that stores historic coverage data (file can contain multiple repos/branches)
+        type: string
+      NEVER_FAIL_AT:
+        type: number
+        default: 0.95
+      AWS_REGION:
+        type: string
+        default: us-east-1
     secrets:
       PKG_TOKEN:
         required: true
-
+      AWS_ACCESS_KEY_ID:
+        required: false
+      AWS_SECRET_ACCESS_KEY:
+        required: false
 
 jobs:
   xunit:
@@ -47,10 +60,79 @@ jobs:
       - name: Run report generation
         run: reportgenerator -reports:$GITHUB_WORKSPACE/*/TestResults/*/coverage.cobertura.xml -targetdir:$RUNNER_TEMP/coverlet/reports -reporttypes:"cobertura"
 
-      - name: Check Branch Coverage
-        id: coverage
+      # Compare against static threshold (BRANCH_THRESHOLD is populated)
+      - name: Check Branch Coverage against static threshold
+        if: ${{ inputs.BRANCH_THRESHOLD > 0 }}
         uses: amdigital-co-uk/code-coverage-action@v1.0
         with:
           path: ${{ runner.temp }}/coverlet/reports/Cobertura.xml
           branch_minimum_threshold: ${{ inputs.BRANCH_THRESHOLD }}
+
+      # Compare against historic coverage (BRANCH_THRESHOLD is empty or 0, AWS secrets populated)
+      # Historic data stored in a CSV file in S3, and is updated if coverage improves.
+      - name: Configure AWS credentials
+        if: ${{ inputs.BRANCH_THRESHOLD <= 0 }}
+        uses: aws-actions/configure-aws-credentials@v1
+        with:
+          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          aws-region: ${{ inputs.AWS_REGION }}
+
+      - name: Check Branch Coverage against historic data
+        if: ${{ inputs.BRANCH_THRESHOLD <= 0 }}
+        env:
+          REPO: ${{ github.repository }}
+          BRANCH: ${{ github.ref_name }}
+          COVERAGE_S3_PATH: ${{ inputs.COVERAGE_S3_PATH }}
+        run: |
+          get_branch() {
+            if [ -f "$1" ]; then
+              cat "$1" | sed -e 's/\r//g' | grep -Po --color=never '<coverage.+branch-rate="\K[^"]+' | head -c 6
+            else
+              echo 0
+            fi
+          }
+
+          [ "$BRANCH" = "main" ] || BRANCH=latest
+          integ_report=$(find . -iname coverage.cobertura.xml | grep "\.IntegrationTest")
+          unit_report=$(find . -iname coverage.cobertura.xml | grep "\.Test")
+
+          total_rate=$(get_branch "$RUNNER_TEMP/coverlet/reports/Cobertura.xml")
+          integ_rate=$(get_branch "$integ_report")
+          unit_rate=$(get_branch "$unit_report")
+          echo "Branch coverage rates for $REPO@${{ github.ref_name }} -- Total: $total_rate, IntegrationTests: $integ_rate, UnitTests: $unit_rate"
+
+          aws s3 cp $COVERAGE_S3_PATH repos.csv
+          record_exists=$(cat repos.csv | grep "^$REPO,$BRANCH," | wc -l)
+
+          if [ "$record_exists" -gt 0 ]
+          then
+            record=$(cat repos.csv | grep "^$REPO,$BRANCH,")
+            
+            total_persist=$(echo $record | cut -d, -f3)
+            integ_persist=$(echo $record | cut -d, -f4)
+            unit_persist=$(echo $record | cut -d, -f5)
+
+            if (( $(echo "$total_persist > $total_rate" | bc -l) ))
+            then
+              if (( $(echo "${{inputs.NEVER_FAIL_AT}} < $total_rate" | bc -l) ))
+              then
+                echo "::notice title=Branch coverage fallen::Test coverage has dropped from $total_persist to $total_rate, but is still above ${{inputs.NEVER_FAIL_AT}} "
+              else
+                echo "::error title=Branch coverage failure::Test coverage has dropped from $total_persist to $total_rate"
+                exit 1
+              fi
+            else
+              echo "SUCCESS: Test coverage maintained from $total_persist to $total_rate"
+            fi
+
+            cat repos.csv | grep -v "^$REPO,$BRANCH," > repos.tmp
+            mv repos.tmp repos.csv
+          else
+            echo "First time coverage reporting for $REPO@$BRANCH"
+          fi
+
+          echo "$REPO,$BRANCH,$total_rate,$integ_rate,$unit_rate" >> repos.csv
+          aws s3 cp repos.csv $COVERAGE_S3_PATH
+          exit 0
 
