Restore xunit.yml, add windows version of sonarcloud

diff --git a/.github/workflows/xunit.yml b/.github/workflows/xunit.yml
--- a/.github/workflows/xunit.yml
+++ b/.github/workflows/xunit.yml
@@ -35,8 +35,7 @@ on:
         required: true
       AWS_ROLE_ARN:
         required: true
-      SONAR_TOKEN:
-        required: true
+
 jobs:
   xunit:
     name: Run XUnit Tests
@@ -45,15 +44,6 @@ jobs:
       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
       - name: Checkout repository
         uses: actions/checkout@v3
-        with:
-          fetch-depth: 0
-          
-      # Static Code Analysis
-      - name: SonarCloud Scan
-        uses: SonarSource/sonarcloud-github-action@master
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
-          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
       
       # Spins up services via Docker-compose
       - name: Start containers
@@ -69,45 +59,127 @@ jobs:
         env:
           NUGET_AUTH_TOKEN: ${{secrets.PKG_TOKEN}}
     
-      # Setup SonarCloud
-      - name: Set up JDK 11
-        uses: actions/setup-java@v1
-        with:
-          java-version: 1.11
-      # - name: Cache SonarCloud packages
-      #   uses: actions/cache@v1
-      #   with:
-      #     path: ~/sonar/cache
-      #     key: ${{ runner.os }}-sonar
-      #     restore-keys: ${{ runner.os }}-sonar
-      # - name: Cache SonarCloud scanner
-      #   id: cache-sonar-scanner
-      #   uses: actions/cache@v1
-      #   with:
-      #     path: ./.sonar/scanner
-      #     key: ${{ runner.os }}-sonar-scanner
-      #     restore-keys: ${{ runner.os }}-sonar-scanner
-      - name: Install SonarCloud scanner
-        if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
-        run: |
-          mkdir -p .sonar/scanner
-          dotnet tool update dotnet-sonarscanner --tool-path .sonar/scanner
-
       # Run Unit Tests
+      - name: Run Unit Tests
+        run: dotnet test --collect:"XPlat Code Coverage"
+
       - name: Install code coverage tool
         run: dotnet tool install --global dotnet-reportgenerator-globaltool
+        
+      - name: Run report generation
+        run: reportgenerator -reports:$GITHUB_WORKSPACE/*/TestResults/*/coverage.cobertura.xml -targetdir:$RUNNER_TEMP/coverlet/reports -reporttypes:"cobertura"
 
-      - name: Run Unit Tests
+      # Compare against static threshold (BRANCH_THRESHOLD is populated)
+      - name: Check Branch Coverage against static threshold
+        if: ${{ inputs.BRANCH_THRESHOLD > 0 }}
+        uses: amdigital-co-uk/code-coverage-action@v1.0
+        with:
+          path: ${{ runner.temp }}/coverlet/reports/Cobertura.xml
+          branch_minimum_threshold: ${{ inputs.BRANCH_THRESHOLD }}
+
+      # Compare against historic coverage (BRANCH_THRESHOLD is empty or 0, AWS secrets populated)
+      # Historic data stored in a CSV file in S3, and is updated if coverage improves.
+      - name: Configure AWS credentials
+        if: ${{ inputs.BRANCH_THRESHOLD <= 0 }}
+        uses: aws-actions/configure-aws-credentials@v1
+        with:
+          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
+          role-duration-seconds: 900
+          aws-region: ${{ inputs.AWS_REGION }}
+
+      - name: Check Branch Coverage against historic data
+        if: ${{ inputs.BRANCH_THRESHOLD <= 0 }}
+        env:
+          REPO: ${{ github.repository }}
+          BRANCH: ${{ github.ref_name }}
+          COVERAGE_S3_PATH: ${{ inputs.COVERAGE_S3_PATH }}
+          NEVER_FAIL_AT: ${{ inputs.NEVER_FAIL_AT }}
+          PERSIST: false
+          DEBUG: ${{ inputs.DEBUG }}
         run: |
-          mv sonar-project.properties sonar-project.tmp
-          .sonar/scanner/dotnet-sonarscanner begin /k:"amdigital-co-uk_testms-netcore2" /o:"amdigital-co-uk" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io"
-          dotnet test --collect "XPlat Code Coverage"
-          reportgenerator -reports:$GITHUB_WORKSPACE/*/TestResults/*/coverage.cobertura.xml -targetdir:. -reporttypes:"SonarQube"
-          .sonar/scanner/dotnet-sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
-          mv sonar-project.tmp sonar-project.properties
+          # Utility Functions
+          log_debug() {
+            if [ "$DEBUG" = "true" ]; then echo $@; fi
+          }
+          get_branch() {
+              if [ -f "$1" ]; then
+                  raw=$(cat "$1" | sed -e 's/\r//g' | grep -Po --color=never '<coverage.+branch-rate="\K[^"]+')
+                  echo "$raw * 100" | bc -l | head -c 6
+              else
+                  echo 0
+              fi
+          }
+          get_record() {
+                  local record=$(cat coverage.csv | grep "^$1,$2,")
+                  [ -z "$record" ] && record=$(cat coverage.csv | grep "^$1,$3,")
+                  echo $record
+          }
+
+          # Set behaviour based on current branch
+          [ "$BRANCH" = "main" ] && PERSIST=true
+          [ "$BRANCH" = "main" ] || BRANCH=latest
+
+          # Retrieve or create coverage CSV
+          aws s3 cp --quiet $COVERAGE_S3_PATH coverage.csv || true
+          if [ ! -f "coverage.csv" ]
+          then
+              log_debug "coverage.csv not present, creating placeholder"
+              echo "Repository,Branch,Total Branch Rate,Integration Branch Rate,Unit Branch Rate"  > coverage.csv
+              PERSIST=true
+          else
+              log_debug "coverage.csv downloaded OK"
+          fi
+
+          # Parse current branch coverage
+          integ_report=$(find . -iname coverage.cobertura.xml | grep "\.IntegrationTest" || true)
+          unit_report=$(find . -iname coverage.cobertura.xml | grep "\.Test" || true)
+          log_debug "integ_report=$integ_report, unit_report=$unit_report"
+          total_rate=$(get_branch "$RUNNER_TEMP/coverlet/reports/Cobertura.xml")
+          integ_rate=$(get_branch "$integ_report")
+          unit_rate=$(get_branch "$unit_report")
+          echo "Branch coverage rates for $REPO@$BRANCH -- Total: $total_rate, IntegrationTests: $integ_rate, UnitTests: $unit_rate"
+
+
+          # Parse historic coverage and cross-check
+          record=$(get_record "$REPO" "main" "latest")
+          log_debug "$record"
+
+          if [ -n "$record" ]
+          then
+              total_persist=$(echo $record | cut -d, -f3)
+              integ_persist=$(echo $record | cut -d, -f4)
+              unit_persist=$(echo $record | cut -d, -f5)
+
+              if (( $(echo "$total_persist > $total_rate" | bc -l) ))
+              then
+                  if (( $(echo "$NEVER_FAIL_AT < $total_rate" | bc -l) ))
+                  then
+                      echo "::notice title=Branch coverage fallen::Test coverage has dropped from $total_persist to $total_rate, but is still above $NEVER_FAIL_AT"
+                  else
+                      echo "::error title=Branch coverage failure::Test coverage has dropped from $total_persist to $total_rate"
+                      exit 1
+                  fi
+              else
+                  echo "::notice title=Branch coverage maintained::Test coverage maintained from $total_persist to $total_rate"
+              fi
+
+              # Remove current coverage values
+              cat coverage.csv | grep -v "^$REPO,$BRANCH," > repos.tmp
+              mv repos.tmp coverage.csv
+          else
+              echo "::notice::First time coverage reporting for $REPO@$BRANCH. Coverage is $total_rate"
+          fi
+
+          # Add new coverage values and persist
+          echo "$REPO,$BRANCH,$total_rate,$integ_rate,$unit_rate" >> coverage.csv
+          [ "$PERSIST" = "true" ] && log_debug "Copying coverage.csv to $COVERAGE_S3_PATH"
+          [ "$PERSIST" = "true" ] && aws s3 cp --quiet coverage.csv $COVERAGE_S3_PATH
+          log_debug "Coverage checking passed"
+
+          exit 0
 
       - name: List files in case of failure
-        #if: failure()
+        if: failure()
         run: |
           find . -iname coverage.cobertura.xml
           find . | grep -v .git/
